# Generated by Django 2.2.1 on 2019-05-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sec1', models.CharField(max_length=20)),
                ('sec2', models.CharField(max_length=20)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('gps', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group_type', models.CharField(choices=[('FELLOWSHIP', 'Fellowship'), ('ADVANCED', 'Advanced'), ('UNION', 'Union')], default='FELLOWSHIP', max_length=10)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remark', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupWithSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.GroupInfo')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.SchoolInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GroupWithChurch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.ChurchInfo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.GroupInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMeetingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(choices=[('SUN', 'SUN'), ('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT')], max_length=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_type', models.CharField(choices=[('REG', 'Regular'), ('BS', 'Bible Study'), ('OTHER', 'Other')], default='REG', max_length=5)),
                ('remark', models.TextField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.GroupInfo')),
            ],
        ),
    ]
