# Generated by Django 2.2.1 on 2019-05-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190516_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchinfo',
            options={'verbose_name': 'Church info', 'verbose_name_plural': 'Church info'},
        ),
        migrations.AlterModelOptions(
            name='groupinfo',
            options={'verbose_name': 'Group info', 'verbose_name_plural': 'Group info'},
        ),
        migrations.AlterModelOptions(
            name='groupmeetingtime',
            options={'verbose_name': 'Group Meeting Time', 'verbose_name_plural': 'Group Meeting Time'},
        ),
        migrations.AlterModelOptions(
            name='groupwithchurch',
            options={'verbose_name': 'Group With Church', 'verbose_name_plural': 'Group With Church'},
        ),
        migrations.AlterModelOptions(
            name='groupwithschool',
            options={'verbose_name': 'Group With School', 'verbose_name_plural': 'Group With School'},
        ),
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name': 'School info', 'verbose_name_plural': 'School info'},
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='address',
            field=models.CharField(max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='gps',
            field=models.IntegerField(default=0, verbose_name='gps'),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='latitude',
            field=models.IntegerField(default=0, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='longitude',
            field=models.IntegerField(default=0, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='sec1',
            field=models.CharField(max_length=20, verbose_name='sec1'),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='sec2',
            field=models.CharField(max_length=20, verbose_name='sec2'),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tel'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='group_type',
            field=models.CharField(choices=[('FELLOWSHIP', 'Fellowship'), ('ADVANCED', 'Advanced'), ('UNION', 'Union')], default='FELLOWSHIP', max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='remark',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tel'),
        ),
        migrations.AlterField(
            model_name='groupmeetingtime',
            name='date',
            field=models.CharField(choices=[('SUN', 'SUN'), ('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT')], max_length=5, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='groupmeetingtime',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='groupmeetingtime',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.GroupInfo', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='groupmeetingtime',
            name='meeting_type',
            field=models.CharField(choices=[('REG', 'Regular'), ('BS', 'Bible Study'), ('OTHER', 'Other')], default='REG', max_length=5, verbose_name='meeting type'),
        ),
        migrations.AlterField(
            model_name='groupmeetingtime',
            name='remark',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='groupmeetingtime',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='groupwithchurch',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.ChurchInfo', verbose_name='church'),
        ),
        migrations.AlterField(
            model_name='groupwithchurch',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.GroupInfo', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='groupwithschool',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.GroupInfo', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='groupwithschool',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.SchoolInfo', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='city',
            field=models.CharField(max_length=20, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='local',
            field=models.CharField(max_length=20, verbose_name='local'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='nick_name',
            field=models.CharField(max_length=50, verbose_name='nick name'),
        ),
    ]
