# Generated by Django 2.2.1 on 2019-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190517_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(verbose_name='group')),
                ('name', models.TextField(verbose_name='name')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=8, verbose_name='gender')),
                ('church', models.TextField(verbose_name='church')),
                ('school', models.TextField(verbose_name='school')),
                ('department', models.TextField(verbose_name='department')),
                ('phone', models.TextField(verbose_name='phone')),
                ('email', models.TextField(verbose_name='email')),
                ('remark', models.TextField(verbose_name='remark')),
            ],
            options={
                'verbose_name': 'Contact Report',
                'verbose_name_plural': 'Contact Report',
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.TextField(verbose_name='issue type')),
                ('content', models.TextField(verbose_name='content')),
                ('name', models.TextField(verbose_name='name')),
                ('email', models.TextField(verbose_name='email')),
            ],
            options={
                'verbose_name': 'Issue Report',
                'verbose_name_plural': 'Issue Report',
            },
        ),
    ]
