# Generated by Django 2.2.1 on 2019-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_contactreport_issuereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreport',
            name='church',
            field=models.CharField(max_length=50, verbose_name='church'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='department',
            field=models.CharField(max_length=50, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='group',
            field=models.CharField(max_length=50, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='school',
            field=models.CharField(max_length=50, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='issue_type',
            field=models.CharField(max_length=20, verbose_name='issue type'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
