# Generated by Django 2.2.1 on 2019-06-20 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190621_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactreport',
            name='reply_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='reply_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuereport',
            name='reply_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='reply_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('UNP', 'Unprocessed'), ('P', 'Processed'), ('O', 'Other')], default='UNP', max_length=20, verbose_name='status'),
        ),
    ]
