# Generated by Django 2.2.1 on 2019-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20190621_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactreport',
            name='status',
            field=models.CharField(choices=[('UNP', 'Unprocessed'), ('PING', 'Processing'), ('PED', 'Processed'), ('O', 'Other')], default='UNP', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='contactreport',
            name='group',
            field=models.CharField(max_length=50, verbose_name='suggestion group'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('UNP', 'Unprocessed'), ('PING', 'Processing'), ('PED', 'Processed'), ('O', 'Other')], default='UNP', max_length=20, verbose_name='status'),
        ),
    ]
